const CHAT_STREAM_TOOL_RULES = 'chat.css';
const EDITOR_PRIMITIVES_RULES = 'editor-primitives.css';

export const kits = [
  {
    id: 'buttons',
    title: 'buttons',
    description: 'Buttons kit: every Btn variant, size and state (primary, secondary, ghost, link, danger, loading, disabled).',
    screenLabel: '17 Buttons',
    htmlTheme: true,
    themeColorMetas: true,
    stylesheets: [],
    importExtra: ['ds/'],
  },
  {
    id: 'aicat',
    title: 'aicat',
    description: 'AICat kit: assistant chat with a cat persona, ascii portrait and thinking dots.',
    screenLabel: '07 AICat',
    htmlTheme: true,
    themeColorMetas: true,
    stylesheets: [CHAT_STREAM_TOOL_RULES, EDITOR_PRIMITIVES_RULES],
    importExtra: ['ds/'],
  },
  {
    id: 'error_404',
    title: '404',
    description: '404 kit: plain not-found page that names the missing path and links to pages that exist.',
    screenLabel: '13 404',
    htmlTheme: true,
    themeColorMetas: true,
    stylesheets: [],
    importExtra: ['ds/'],
  },
  {
    id: 'gallery',
    title: 'gallery',
    description: 'Gallery kit: visual grid, lightbox and tonal cards.',
    screenLabel: '14 Gallery',
    htmlTheme: true,
    themeColorMetas: true,
    stylesheets: [EDITOR_PRIMITIVES_RULES],
    importExtra: ['ds/'],
  },
  {
    id: 'search',
    title: 'search',
    description: 'Search kit: query bar, faceted filters and ranked results.',
    screenLabel: '12 Search',
    htmlTheme: true,
    themeColorMetas: true,
    stylesheets: [],
    importExtra: ['ds/'],
  },
  {
    id: 'settings',
    title: 'settings',
    description: 'Settings kit: sectioned forms, toggles, inputs and a save bar.',
    screenLabel: '10 Settings',
    htmlTheme: true,
    themeColorMetas: true,
    stylesheets: [EDITOR_PRIMITIVES_RULES],
    importExtra: ['ds/'],
  },
  {
    id: 'slide_deck',
    title: 'slide deck',
    description: '16:9 slide deck template with keyboard navigation, a slide counter and SDK chrome.',
    screenLabel: '17 Slide Deck',
    htmlTheme: true,
    themeColorMetas: true,
    stylesheets: [],
    importExtra: ['ds/'],
  },
  {
    id: 'system_primer',
    title: 'system primer',
    description: 'Design system showcase: palette swatches, type scale and primitives on one page.',
    screenLabel: '16 System Primer',
    htmlTheme: true,
    themeColorMetas: true,
    stylesheets: [EDITOR_PRIMITIVES_RULES],
    importExtra: ['ds/'],
  },
  {
    id: 'terminal',
    title: 'terminal',
    description: 'Terminal kit: cli prompt, command lines and a log viewer.',
    screenLabel: '09 Terminal',
    htmlTheme: true,
    themeColorMetas: true,
    stylesheets: [],
    importExtra: ['ds/'],
  },
  {
    id: 'gm_inspector',
    title: 'gm inspector',
    description: 'GM Inspector kit: session list, process tree, deviations, PRD and mutable editors, and a query builder, built from AppShell and the data-density components.',
    screenLabel: 'gm inspector',
    htmlTheme: true,
    themeColorMetas: true,
    stylesheets: [EDITOR_PRIMITIVES_RULES],
    importExtra: ['ds/'],
  },
  {
    id: 'dashboard',
    title: 'dashboard',
    description: 'Dashboard kit: kpis, tables, receipts, a changelog and panels.',
    screenLabel: '08 Dashboard',
    htmlTheme: true,
    themeColorMetas: true,
    stylesheets: [EDITOR_PRIMITIVES_RULES],
    importExtra: ['ds/'],
  },
  {
    id: 'signin',
    title: 'sign in',
    description: 'Sign in kit: authentication panel, providers and a tonal form.',
    screenLabel: '11 Sign in',
    htmlTheme: true,
    themeColorMetas: true,
    stylesheets: [EDITOR_PRIMITIVES_RULES],
    importExtra: ['ds/'],
  },
  {
    id: 'homepage',
    title: 'homepage',
    description: 'Landing page for the 247420 collective: works, writing and manifesto.',
    screenLabel: '01 Homepage',
    htmlTheme: true,
    themeColorMetas: true,
    stylesheets: [],
    importExtra: ['ds/'],
    seo: {
      author: '247420 / AnEntrypoint',
      keywords: '247420, anentrypoint, design system, webjsx, rippleui, creative collective',
      ogImage: true,
      twitter: true,
    },
  },
  {
    id: 'project_page',
    title: 'project / design ·',
    titleSuffixed: true,
    description: 'Generic project landing template: install, receipt, changelog and docs sidebar.',
    screenLabel: '02 Project Page',
    htmlTheme: true,
    themeColorMetas: true,
    stylesheets: [],
    importExtra: ['ds/'],
    seo: {
      author: '247420 / AnEntrypoint',
      keywords: '247420, anentrypoint, design system, webjsx, rippleui, creative collective',
      ogImage: true,
      twitter: true,
    },
  },
  {
    id: 'file_browser',
    title: 'file browser',
    description: 'File browser: rails by file type, drop-zone upload and modal preview.',
    screenLabel: '08 File Browser',
    htmlTheme: true,
    themeColorMetas: true,
    stylesheets: [CHAT_STREAM_TOOL_RULES, EDITOR_PRIMITIVES_RULES],
    importExtra: [],
    seo: {
      author: '247420 / AnEntrypoint',
      ogSimple: true,
    },
  },
];
