export const PREVIEW_GROUPS = ['Color', 'Type and spacing', 'Components', 'File browser', 'Brand', 'Reference'];

export const PREVIEWS = [
  { name: 'colors-core', group: 'Color', title: 'core colors', description: 'the four base swatches: paper, ink and their two shades each.' },
  { name: 'colors-lore', group: 'Color', title: 'palette tokens', description: 'the raw palette tokens, including the legacy-named ones.' },
  { name: 'colors-semantic', group: 'Color', title: 'semantic colors', description: 'role tokens (link, warn, on-color) that components use instead of raw hex.' },
  { name: 'theme-ink', group: 'Color', title: 'ink theme', description: 'the dark theme: how paper and ink invert while the accent stays put.' },
  { name: 'type-display', group: 'Type and spacing', title: 'display type', description: 'hero and section headlines in the system sans, with size and tracking.' },
  { name: 'type-mono', group: 'Type and spacing', title: 'mono type', description: 'labels, meta text and body in the platform monospace.' },
  { name: 'type-prose', group: 'Type and spacing', title: 'prose type', description: 'long-form paragraph styling: measure, leading and emphasis.' },
  { name: 'type-scale', group: 'Type and spacing', title: 'type scale', description: 'every font-size step from mega down to micro, rendered at size.' },
  { name: 'spacing', group: 'Type and spacing', title: 'spacing scale', description: 'the 8pt spacing steps with their pixel values.' },
  { name: 'rules', group: 'Type and spacing', title: 'rules', description: 'single, double and dotted hairlines and when to use each.' },
  { name: 'buttons', group: 'Components', title: 'buttons', description: 'every button variant, size and state, with the tokens each uses.' },
  { name: 'inputs', group: 'Components', title: 'inputs', description: 'hairline text fields: label, placeholder, focus and error states.' },
  { name: 'index-row', group: 'Components', title: 'index row', description: 'the numbered list row used for works, posts and projects.' },
  { name: 'panel-rows', group: 'Components', title: 'panel rows', description: 'trio, duo and flush panel rows that step down on container width.' },
  { name: 'data-density', group: 'Components', title: 'data density', description: 'dense table, meter and list components for operational screens.' },
  { name: 'editor-primitives', group: 'Components', title: 'editor primitives', description: 'building blocks for editors: toolbars, toasts, aspect ratios and more.' },
  { name: 'content', group: 'Components', title: 'content primitives', description: 'hero, panel, list and manifesto blocks used on content pages.' },
  { name: 'header', group: 'Components', title: 'header', description: 'the sticky top bar and breadcrumb with nav hover states.' },
  { name: 'stamps', group: 'Components', title: 'stamps', description: 'four rotated status stamp variants.' },
  { name: 'dateline', group: 'Components', title: 'dateline', description: 'the brand dateline strip shown at the top of a page.' },
  { name: 'file-row', group: 'File browser', title: 'file row', description: 'one file: type rail, icon, name, meta and actions.' },
  { name: 'file-grid', group: 'File browser', title: 'file grid', description: 'a stack of file rows with directories first and a selected state.' },
  { name: 'file-toolbar', group: 'File browser', title: 'file toolbar', description: 'breadcrumb, upload actions and item count.' },
  { name: 'file-viewer', group: 'File browser', title: 'file viewer', description: 'full-bleed modal preview with syntax highlighting and actions.' },
  { name: 'dropzone', group: 'File browser', title: 'drop zone', description: 'upload target with idle and drag-over states and no dashed border.' },
  { name: 'wordmarks', group: 'Brand', title: 'wordmarks', description: 'typographic project wordmarks; there are no pictorial marks.' },
  { name: 'manifesto', group: 'Brand', title: 'manifesto block', description: 'numbered statement paragraphs as used on the homepage.' },
  { name: 'stamps-lore', group: 'Brand', title: 'brand stamps', description: 'the full set of brand stamps, including the playful ones.' },
  { name: 'icons-unicode', group: 'Reference', title: 'unicode glyph set', description: 'the small set of plain unicode symbols allowed in copy.' },
  { name: 'theme-map', group: 'Reference', title: 'theme token map', description: 'every root token, its default value and which sheets consume it.' },
];

export const previewByName = new Map(PREVIEWS.map((p) => [p.name, p]));
